//Cancer Recoding of open text 
function exactMatch(cancerType){
  
  return cancerType.trim().map({
        'BLADDER': 'BLADDER',
        'BLADDER CANCER': 'BLADDER',
        'BLADDER TUMOR' : 'BLADDER',
        'BRAIN': 'BRAIN',
        'BRAIN CANCER' : 'BRAIN',
        'BRAIN TUMOUR': 'BRAIN',
        'BRAIN TUMOR': 'BRAIN',
        'BRAIN TUMERS': 'BRAIN',
        'CERVEAU': 'BRAIN',
        'BREAST': 'BREAST',
        'SEIN':'BREAST',
        'BREAST CANCER': 'BREAST',
        'BREATS' : 'BREAST',
        'BREAT' : 'BREAST',
        'CERVIX': 'CERVIX',
        'CERVICAL': 'CERVIX',
        'CERVIX CANCER' : 'CERVIX',
        'CERVICAL CANCER' : 'CERVIX',
        'COLON': 'COLON',
        'COLIN': 'COLON',
        'COLON CANCER': 'COLON',
        'ESOPHAGUS': 'ESOPHAGUS',
        'OESOPHAGUS' : 'ESOPHAGUS',
        'ESOPHAGEAL' : 'ESOPHAGUS',
        'OESOPHAGE': 'ESOPHAGUS',
        'ESOPHAGEAL CANCER ': 'ESOPHAGUS',
        'ESOPHAGUS CANCER': 'ESOPHAGUS',
        'OESOPHAGUS CANCER': 'ESOPHAGUS',
        'ESOPHGAS': 'ESOPHAGUS',  
        'ESPHAGUS' : 'ESOPHAGUS',  
        'KIDNEY': 'KIDNEY',
        'KIDNEY CANCER': 'KIDNEY',
        'KIDNEY TUMOR': 'KIDNEY', 
        'LARYNX': 'LARYNX',
        'LARYNX CANCER' : 'LARYNX',
        'LARNYX': 'LARYNX',
        'LEUKEMIA': 'LEUKEMIA',
        'CHRONIC LEUKEMIA': 'LEUKEMIA',
        'LEUCÉMIE': 'LEUKEMIA',
        'LEUKIMIA': 'LEUKEMIA',
        'LIVER': 'LIVER',
        'LIVER CANCER' : 'LIVER',
        'LUNG': 'LUNG',
        'LUNG CANCER': 'LUNG',
        'BRONCHUS AND LUNG' : 'LUNG',
        'LYMPHOMA':'LYMPHOMA',
        'NHL': 'NHL',
        'NON HODGKINS LYMPHOMA': 'NHL',
        'NON-HODGKIN\'S LYMPHOMA': 'NHL',
        'NON-HODGKINS LYMPHOMA': 'NHL',
        'OVARY': 'OVARY',
        'OVARY CANCER' : 'OVARY',
        'OVARY TUMOR': 'OVARY',
        'OVARIAN': 'OVARY',
        'OVARIAN CANCER': 'OVARY',
        'PANCREAS': 'PANCREAS',
        'PANCREATIC': 'PANCREAS',
        'CANCER OF PANCREAS': 'PANCREAS',
        'PANCREAS CANCER' : 'PANCREAS',
        'PROSTATE': 'PROSTATE',
        'PROSTRATE': 'PROSTATE',
        'PROSTATE CANCER': 'PROSTATE',
        'RECTUM': 'RECTUM',
        'RECTAL': 'RECTUM',
        'RECTAL CANCER': 'RECTUM',
        'RECTUM CANCER' : 'RECTUM',
        'SKIN': 'SKIN',
        'SKIN CANCER': 'SKIN',
        'PEAU': 'SKIN',
        'STOMACH': 'STOMACH',
        'STOMACH CANCER' : 'STOMACH',
        'STOMACH TUMOR': 'STOMACH',
        'STOMACHE': 'STOMACH',
        'STPMACH': 'STOMACH',
        'ESTOMAC': 'STOMACH',
        'THYROID': 'THYROID',
        'THYROIDE': 'THYROID',
        'THYROID CANCER' : 'TYHROID',
        'CANCER DE LA GLANDE THYROIDIENNE': 'THYROID',
        'GLANDE THYORÏDE': 'THYROID',
        'TRACHEA': 'TRACHEA',
        'TRACHEA CANCER' : 'TRACHEA',
        'UTERUS': 'UTERUS',
        'UTERUS CANCER' : 'UTERUS',
        'UTERINE': 'UTERUS',
        'TUMOR IN UTERUS' : 'UTERUS',
        'OTHER': 'OTHER',
        'DON\'T KNOW': null,
        'DNK' : null,
        '?' : null,
        'NA': null,
        'NOT SURE': null,  
        }, 'OTHER',null);
}

/*
Code to other for now
  'PARATHYROID GLAND': 'THYROID',
  'CEVERIAL': 'CERVIX',
  'PANCREAS (TERMINAL)': 'PANCREAS'
  'SKIN   VERY TREATABLE': 'SKIN',
  'SKIN NOT SPECIFIED': 'SKIN',
  'SKIN NOT  SPECIFIED': 'SKIN',
  'SKIN UNSPECIFIED': 'SKIN',
  'SKING NOT SPECIFIED': 'SKIN',
  'SKINI NOT SPECIFIED': 'SKIN',
  'SKIN CANCER NOT SPECIFIED': 'SKIN',
  'BASAL CELL SKIN' : 'SKIN' //To validate (type of skin cancer)
  'SQUAMOUS CELL SKIN' : 'SKIN' //To validate (type of skin cancer)
*/