#### Statistics

```{r, echo=FALSE}
value <- opal.execute(o, paste0("(D$", variable$name, ")"))
value2<-value    ##create a copy of value
for(category in variable$categories){
  if (category$isMissing){
    value[which(value==category$name)]<-NA
    
  }
}
summary<-summary(value2)
NValid <- length(which(!is.na(value)))
NTotal <- length(value2)
NMissing<-length(which(is.na(value)))
```

Descriptive Statistic | Value
--------------------- | ----------------
N                     | `r NValid`
Mode                  | `r names(summary[which.max(summary)])`

```{r, results='asis', echo=FALSE}
cat('Value| Frequency| Subtotal percentage|Total percentage\n')                             
cat('----- | --------| -------------------| ---------------\n')
cat('__Non-missing__ |      \n')
for (category in variable$categories) {
  if(!category$isMissing){
    catname<-category$name
    catCount <- as.numeric(summary[catname])
    pctSub <- round((catCount/NValid)*100,2)
    pctTot<- round((catCount/NTotal)*100,2)
    cat(paste0(catname, " | ", catCount," | ", pctSub,"%|",pctTot," %\n"))
  }
}
cat(paste0('_Subtotal_ |',NValid,'|',100,'% |',round((NValid/NTotal)*100,2),'%\n')) #<---display subTotalvalid stats
cat('__Missing__    |       \n')
for (category in variable$categories) { 
  if(category$isMissing){
    catname<-category$name
    catCount<-as.numeric(summary[catname])
    pctSub<-ifelse(NMissing==0,0,round((length(which(value2==catname)))/NMissing*100,2))
    pctTot<-ifelse(NMissing==0,0,round((length(which(value2==catname)))/NTotal*100,2))
    cat(paste0(catname,'|',catCount,'|',pctSub,'%|',pctTot,'%\n')) 
  }
}

naCount <- as.numeric(summary["NA's"])
naCount<-ifelse(is.na(naCount),0,naCount)
NaSubPct<-ifelse(NMissing==0,0,round(naCount/NMissing*100,2))
NaTotPct<-ifelse(NTotal==0,0,round(naCount/NTotal*100,2))
cat(paste0('N/A |',naCount,'|',NaSubPct,'% |',NaTotPct,'%\n'))  #<----display na stats
missingTotal<-length(which(is.na(value)))
TotSubMissingPct<-ifelse(NMissing==0,0,round(missingTotal/NMissing*100,2))
TotTotMissingPct<-ifelse(NTotal == 0,0,round(missingTotal/NTotal*100,2))
cat(paste0('_Subtotal_ |',length(which(is.na(value))),'|',TotSubMissingPct,'% |',TotTotMissingPct,'%\n')) #<---display subTotalmissing stats
cat(paste0('__Total__ |',NTotal,'|','-',' |',100,'%\n')) #<---display Total stats

```

```{r, echo=FALSE, eval=withGraphs & !allIsNA}
# see http://docs.ggplot2.org/current/geom_bar.html
#opal.execute(o, paste0("qplot(", variable$name,", data=D)"))
opal.execute(o, paste0("qplot(",variable$name, ", data=D,geom='bar',colour=I('white'),fill=",variable$name,")+scale_fill_hue(na.value='grey50',direction=1)"))
```
