#### Statistics

```{r,echo=FALSE}
value<-opal.execute(o,paste0("D$",variable$name))
value2<-value
```

```{r, echo=FALSE,eval= !hasNonMissingCategory}
for(category in variable$categories){
  if (category$isMissing){
    value[which(value==category$name)]<-NA
    
  }
}
```

```{r,echo=FALSE}
NotMissing<-length(which(!is.na(value)))
NTotal<-length(value2)
NMissing<-length(which(is.na(value)))

```

Descriptive Statistic | Value
--------------------- | ----------------
N                     | `r NotMissing`
Min                   | `r min(value,na.rm=T)`
Max                   | `r max(value,na.rm=T)`
Mean                  | `r mean(value,na.rm=T)`
Median                | `r median(value,na.rm=T)`
Standard Deviation    | `r sd(value,na.rm=T)`
Variance              | `r var(value,na.rm=T)`
Skewness              | `r skewness(value,na.rm=T)`
Kurtosis              | `r kurtosis(value,na.rm=T)`
Sum                   | `r sum(value,na.rm=T)`
Sum of squares        | `r sum(value^2,na.rm=T)`

<br/>


```{r,echo=FALSE,results='asis' }
cat('Value| Frequency| Subtotal percentage|Total percentage\n')                             
cat('----- | --------| -------------------| ---------------\n')
cat('__Non-missing__ |      \n')
statpart1<-paste0('Not empty |',NotMissing,'|',round(NotMissing/NotMissing*100,2),'% |',round(NotMissing/NTotal*100,2),'%\n')
cat(statpart1)
cat('__Missing__    |       \n')
if(!hasNonMissingCategory ){
  for (cat in variable$categories) { 
    if(category$isMissing){
      cn<-cat$name
      catCount<-length(which(value2==cn))
      catSubFreq<-ifelse(NMissing==0,0,round((length(which(value2==cn)))/NMissing*100,2))
      catTotFreq<-ifelse(NMissing==0,0,round((length(which(value2==cn)))/NTotal*100,2))
      outputstat<-paste0(cn,'|',catCount,'|',catSubFreq,'%|',catTotFreq,'%')
      cat(paste0(outputstat,'\n'))
    }
  }
}
NaSubFreq<-ifelse(NMissing==0,0,round((length(which(is.na(value2))))/NMissing*100,2))
NaTotFreq<-ifelse(NTotal==0,0,round((length(which(is.na(value2))))/NTotal*100,2))
cat(paste0('N/A |',length(which(is.na(value2))),'|',NaSubFreq,'% |',NaTotFreq,'%\n'))
TotSubMissingFreq<-ifelse(NMissing==0,0,round((length(which(is.na(value))))/NMissing*100,2))
TotTotMissingFreq<-ifelse(NTotal == 0,0,round((length(which(is.na(value))))/NTotal*100,2))
cat(paste0('_Subtotal_ |',length(which(is.na(value))),'|',TotSubMissingFreq,'% |',TotTotMissingFreq,'%\n')) #<---display subtotalmissing
cat(paste0('__Total__ |',NTotal,'|','-',' |',100,'%\n')) #<---display Total stats
```



```{r, echo=FALSE, eval=withGraphs}
# see http://docs.ggplot2.org/current/geom_histogram.html
#plot(opal.execute(o, paste0("hist(D$", variable$name,")")))
bin<-(max(value,na.rm=T)-min(value,na.rm=T))/20
#opal.execute(o, paste0("qplot(", value,",geom='histogram',binwidth=" ,bin, ",fill=I('lightblue3'),colour=I('yellow'),xlab=",variable$name,")"))
qplot(value,geom='histogram',xlab=variable$name,binwidth=bin,fill=I('lightblue3'),colour=I('yellow'))
```
