### `r variable$name`

```{r results=FALSE,echo=FALSE}
hasCategories <- (length(variable$categories) > 0)
hasAttributes <- (length(variable$attributes) > 0)
hasNonMissingCategory <- FALSE
if (hasCategories) {
  for (category in variable$categories) {
    if (!category$isMissing) {
      hasNonMissingCategory <- TRUE      
      break;
    }
  }
}
isCategorical <- (hasCategories & hasNonMissingCategory) | variable$valueType == 'boolean'
isNumerical <- (variable$valueType == 'integer' | variable$valueType == 'decimal') & !isCategorical
allIsNA <- TRUE
if (withStatistics) {
  allIsNA <- opal.execute(o, paste0("all(is.na(D$", variable$name, "))"))
}
```

#### Properties

Property         | Value  
---------------- | ----------------
label            | `r gsub('\\\n','<br/>',paste(opal.attribute_values(variable$attributes, name="label"), collapse="<br/>"))`
definition       | `r gsub('\\\n','<br/>',paste(opal.attribute_values(variable$attributes, name="description"),collapse='<br/>'))`
Value type       | `r variable$valueType`
Unit             | `r variable$unit`
Entity type      | `r variable$entityType`


#### Attributes

Property         | Value  
-----------------| ----------------
Mlstr_harmo:status      | `r opal.attribute_values(variable$attributes, namespace="Mlstr_harmo", name="status")`

```{r, results='asis', eval=hasCategories, echo=FALSE}
cat("#### Categories\n")
```

```{r, results='asis', eval=hasCategories, echo=FALSE}
cat("Name | Label | Missing\n")
cat("---------------- | ---------------- | ----------------\n")
for (category in variable$categories) {
  labels <- paste(opal.attribute_values(category$attributes, name="label"), collapse="<br/>")
  row <- paste0(category$name, " | ", gsub("\\|","/", labels) ," | ")
  if (category$isMissing) {
    row <- paste0(row, "<span class='glyphicon glyphicon-ok'></span>")
  }
  cat(paste0(row, "\n"))
}
```

```{r, results='asis', eval=withStatistics & allIsNA, echo=FALSE}
cat("#### Statistics\n")
cat("All participants are missing values: No statistics available\n")
```

```{r, results='asis',eval= identical(variable$valueType,'text') & withStatistics & !allIsNA & !hasCategories, echo=FALSE }
cat("#### Statistics\n")
cat("No statistics are displayed for open text type variable\n")
```

```{r, include=FALSE, eval=withStatistics & isCategorical & !allIsNA,results='hide'} 
outsummary <- knit_child('opal-variable-categorical.Rmd')
```

```{r, include=FALSE, eval=withStatistics & isNumerical & !allIsNA,results='hide'}
outsummary <- knit_child('opal-variable-continuous.Rmd')
```

`r if(withStatistics & (isNumerical | isCategorical) & !allIsNA) paste(outsummary, collapse='\n')`